config/routes.rb
Rails.application.routes.draw do
  root 'dogs#index'
  resources :dogs, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @breed = params[:breed]
    @dog_picture = get_dog_picture(@breed)

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def get_dog_picture(breed)
    return nil if breed.nil?  # Handle the case where breed is nil

    url = "https://dog.ceo/api/breed/#{breed.downcase}/images/random"
    response = RestClient.get(url)
    data = JSON.parse(response.body)

    data['message'] # This will be the URL of the dog picture
  rescue RestClient::ExceptionWithResponse => e
    nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/index.html.erb
<!-- app/views/dogs/index.html.erb -->
<div class="container">
  <div class="content-wrapper">
    <div class="form-container">
      <h1>Displaying Dog Picture</h1>
<!-- app/views/dogs/index.html.erb -->
<%= form_tag(dogs_path, method: "get", remote: true, data: { controller: 'dog' }) do %>
<%= text_field_tag(:breed, params[:breed], placeholder: "Enter dog breed") %>
  <%= submit_tag("Get Dog Picture", data: { action: 'click->dogs#submitForm' }) %>
<% end %>

      <% if @breed.present? %>
        <p>Submitted Dog Breed: <%= @breed.capitalize %></p>
      <% end %>
    </div>

    <div class="image-container">
      <% if @dog_picture.present? %>
        <img src="<%= @dog_picture %>" alt="Dog Picture">
      <% else %>
        <p>No picture available for the specified breed.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogBreed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>